console.debug('ContractFormModel');

export default {
    errors: {
        account: [],
        token_name: [],
        token_symbol: [],
        token_decimals: [],
        initial_supply: [],
        total_supply: [],
        access_type: [],
        supply_type: [],
        is_verified_source_code: [],
        is_copyright_off: [],
        is_token_burnable: [],
        is_token_mintable: [],
        is_operable: [],
        is_token_recoverable: [],
        token_type: [],
        token_network: [],
        is_agreement_checked: [],
    },
    is_total_supply_disabled_attr: true,
    is_supply_type_disabled_attr: true,
    is_access_type_disabled_attr: true,
    is_verified_source_code_disabled_attr: true,
    is_copyright_off_disabled_attr: true,
    is_token_burnable_disabled_attr: true,
    is_token_mintable_disabled_attr: true,
    is_operable_disabled_attr: true,
    is_token_recoverable_disabled_attr: true,
    is_token_type_disabled_attr: false,
    is_token_network_disabled_attr: true,
    contract_address: "",
    transaction_hash: "",
    is_submitting: false,
}
